# Generated by Django 2.2 on 2019-04-07 04:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CMSApp', '0008_auto_20190406_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 4, 2, 23, 140498, tzinfo=utc)),
        ),
    ]
